services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/backe
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: vasil
    restart: always 

  db:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: backe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vasil
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  db_data:
