name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Triggers the pipeline when changes are pushed to the `main` branch
  pull_request:
    branches:
      - main  # Triggers the pipeline on pull requests targeting the `main` branch

env:
  REGISTRY: docker.io  # DockerHub registry
  IMAGE_NAME: ivamakenadjieva/kiii_food_app:latest  # Update with your DockerHub username and image name

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # Grant permission to read repository content
      packages: write  # Grant permission to push to DockerHub
      id-token: write  # Allow the job to interact with ID tokens if needed (optional)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out the repository's code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Sets up Docker Buildx for multi-platform builds

      - name: Log into DockerHub
        uses: docker/login-action@v2  # Logs in to DockerHub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # DockerHub username stored in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # DockerHub password stored in GitHub Secrets

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .  # Builds the Docker image using the Dockerfile in the repository

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}  # Pushes the Docker image to DockerHub

