name: Test DockerHub Login

on:
  workflow_dispatch:  

jobs:
  test-login:
    name: Test DockerHub Secrets & Login
    runs-on: ubuntu-latest

    steps:
      - name: Print Debug Info (Without Exposing Secrets)
        run: |
          echo "Testing if secrets are available..."
          echo "DOCKERHUB_USERNAME is set: ${{ secrets.DOCKERHUB_USERNAME != '' }}"
          echo "DOCKERHUB_TOKEN is set: ${{ secrets.DOCKERHUB_TOKEN != '' }}"

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test Docker Login
        run: |
          echo "Testing DockerHub authentication..."
          docker info | grep -i "username" || echo "Login failed!"
