name: Build and Push Docker Image

on:
  push:
    branches:
      - master

permissions:
  contents: read      
  packages: write     
  id-token: write     

jobs:
  build: 
    name: Build JAR File
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build the JAR File
        run: |
          echo "Building FoodApp..."
          cd backend  # Ensure we navigate to the backend directory
          mvn clean package -DskipTests
          ls -lh target/

      - name: Upload JAR as an Artifact
        uses: actions/upload-artifact@v4  # Corrected to v4
        with:
          name: foodapp-jar
          path: target/*.jar
          retention-days: 1

  dockerize:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download JAR Artifact
        uses: actions/download-artifact@v4  # Updated to v4
        with:
          name: foodapp-jar
          path: target/

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: ivamakenadjieva/kiii_food_app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Building Docker Image..."
          docker build --pull --no-cache -t $IMAGE_NAME:$IMAGE_TAG .
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
          echo "Pushing to DockerHub..."
          docker push $IMAGE_NAME:$IMAGE_TAG || echo "Failed to push versioned image!"
          docker push $IMAGE_NAME:latest || echo "Failed to push latest image!"
